FROM --platform=linux/amd64 node:20-bullseye-slim

WORKDIR /app

COPY . .

ARG NEXT_PUBLIC_APP_ID
ARG NEXT_PUBLIC_APP_KEY
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_APP_TYPE_WORKFLOW

ENV NEXT_PUBLIC_APP_ID=$NEXT_PUBLIC_APP_ID
ENV NEXT_PUBLIC_APP_KEY=$NEXT_PUBLIC_APP_KEY
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_APP_TYPE_WORKFLOW=$NEXT_PUBLIC_APP_TYPE_WORKFLOW

RUN yarn install
RUN yarn build

EXPOSE 3000

CMD ["yarn","start"]
